-- Exercise the actual RPCs as students, teachers and administrators.
BEGIN;
UPDATE users SET status='active' WHERE id IN ('00000000-0000-4000-8000-000000000001','00000000-0000-4000-8000-000000000002','00000000-0000-4000-8000-000000000003');
CREATE TEMP TABLE public_qa(id uuid, replacement uuid);
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000003',false);
UPDATE live_bookings SET status='cancelled',credit_used=false WHERE user_id=auth.uid();
INSERT INTO public_qa(id) SELECT book_live_lesson('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',current_date+60,'10:00');
SELECT test_assert((SELECT status='pending' AND credit_used FROM live_bookings WHERE id=(SELECT id FROM public_qa)),'new request holds a credit pending approval');
SELECT test_assert((SELECT x->>'status'='pending' AND x->>'zoom'='' FROM jsonb_array_elements(live_workspace()->'bookings') x WHERE x->>'id'=(SELECT id::text FROM public_qa)),'pending student view hides meeting link');
SELECT test_reject(format('SELECT update_live_booking(%L,''approve'')',(SELECT id FROM public_qa)),'Only administration');
SELECT test_reject($$SELECT book_live_lesson('10000000-0000-4000-8000-000000000001','20000000-0000-4000-8000-000000000001',current_date+1,'10:00')$$,'no longer available');
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',false);
SELECT test_reject(format('SELECT update_live_booking(%L,''approve'')',(SELECT id FROM public_qa)),'Only administration');
SELECT test_reject(format('SELECT update_live_booking(%L,''no_show'')',(SELECT id FROM public_qa)),'confirmed');
SELECT test_reject(format('SELECT save_live_teacher((SELECT profile||jsonb_build_object(''revision'',revision,''daysOff'',jsonb_build_array(%L)) FROM live_teachers LIMIT 1))',(current_date+60)::text),'Time off conflicts');
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',false);
SELECT test_reject(format('SELECT update_live_booking(%L,''approve'')',(SELECT id FROM public_qa)),'course end');
SELECT save_live_course_terms((SELECT enrollment_id FROM live_bookings WHERE id=(SELECT id FROM public_qa)),now()+interval '100 days',now()+interval '130 days');
SELECT update_live_booking((SELECT id FROM public_qa),'approve');
SELECT update_live_booking((SELECT id FROM public_qa),'approve');
SELECT test_assert((SELECT status='booked' AND approved_by=auth.uid() FROM live_bookings WHERE id=(SELECT id FROM public_qa)),'admin approval is recorded and idempotent');
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000003',false);
-- 48–72 hours: cancellation permitted but charged.
UPDATE live_bookings SET starts_at=now()+interval '60 hours',ends_at=now()+interval '60 hours 30 minutes' WHERE id=(SELECT id FROM public_qa);
SELECT test_assert((SELECT (x->>'canCancel')::boolean AND NOT (x->>'cancelReturnsCredit')::boolean FROM jsonb_array_elements(live_workspace()->'bookings') x WHERE x->>'id'=(SELECT id::text FROM public_qa)),'student sees the late-cancellation credit warning');
SELECT update_live_booking((SELECT id FROM public_qa),'cancel');
SELECT update_live_booking((SELECT id FROM public_qa),'cancel');
SELECT test_assert((SELECT status='cancelled' AND credit_used FROM live_bookings WHERE id=(SELECT id FROM public_qa)),'late cancellation retains exactly one credit');
UPDATE live_bookings SET status='booked',starts_at=now()+interval '72 hours',ends_at=now()+interval '72 hours 30 minutes' WHERE id=(SELECT id FROM public_qa);
SELECT update_live_booking((SELECT id FROM public_qa),'cancel');
SELECT test_assert((SELECT NOT credit_used FROM live_bookings WHERE id=(SELECT id FROM public_qa)),'exactly 72 hours returns credit');
UPDATE live_bookings SET status='booked',credit_used=true,starts_at=now()+interval '47 hours',ends_at=now()+interval '47 hours 30 minutes' WHERE id=(SELECT id FROM public_qa);
SELECT test_reject(format('SELECT update_live_booking(%L,''cancel'')',(SELECT id FROM public_qa)),'48 hours');
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000002',false);
SELECT update_live_booking((SELECT id FROM public_qa),'cancel');
SELECT test_assert((SELECT NOT credit_used AND cancellation_reason='teacher' FROM live_bookings WHERE id=(SELECT id FROM public_qa)),'teacher cancellation always refunds');
-- Failed replacement must roll back both credit and reservation changes.
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000003',false);
UPDATE live_bookings SET status='booked',credit_used=true,starts_at=now()+interval '60 hours',ends_at=now()+interval '60 hours 30 minutes' WHERE id=(SELECT id FROM public_qa);
SELECT test_reject(format('SELECT reschedule_live_lesson(%L,current_date+1,''10:00'')',(SELECT id FROM public_qa)),'no longer available');
SELECT test_assert((SELECT status='booked' AND credit_used FROM live_bookings WHERE id=(SELECT id FROM public_qa)),'failed replacement preserves old reservation');
UPDATE public_qa SET replacement=reschedule_live_lesson(id,current_date+61,'10:00');
SELECT test_assert((SELECT status='cancelled' AND credit_used AND cancellation_reason='rescheduled' FROM live_bookings WHERE id=(SELECT id FROM public_qa)),'late reschedule charges old credit');
SELECT test_assert((SELECT status='pending' AND credit_used AND rescheduled_from=(SELECT id FROM public_qa) FROM live_bookings WHERE id=(SELECT replacement FROM public_qa)),'replacement pending approval consumes additional credit');
SELECT test_reject(format('SELECT reschedule_live_lesson(%L,current_date+62,''10:00'')',(SELECT id FROM public_qa)),'48 hours');
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000001',false);
SELECT update_live_booking((SELECT replacement FROM public_qa),'reject');
SELECT test_assert((SELECT NOT credit_used AND cancellation_reason='rejected' FROM live_bookings WHERE id=(SELECT replacement FROM public_qa)),'rejected request returns held credit');
-- Media and course terms are checked per enrollment, never just per product.
UPDATE live_bookings SET status='completed',starts_at=now()-interval '2 hours',ends_at=now()-interval '90 minutes' WHERE id=(SELECT id FROM public_qa);
INSERT INTO live_assets(kind,course_id,booking_id,teacher_id,title,filename,mime_type,byte_size,provider,state,uploaded_by)
 SELECT 'recording',course_id,id,teacher_id,'Public workflow QA','qa.mp4','video/mp4',100,'vimeo','ready',auth.uid() FROM live_bookings WHERE id=(SELECT id FROM public_qa);
SELECT save_live_course_terms((SELECT enrollment_id FROM live_bookings WHERE id=(SELECT id FROM public_qa)),now()+interval '10 days',now()+interval '20 days');
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000003',false);
SELECT test_assert(live_recording_access((SELECT id FROM live_assets WHERE title='Public workflow QA'),false),'playback throughout course');
SELECT test_assert(live_recording_access((SELECT id FROM live_assets WHERE title='Public workflow QA'),true),'authorized download');
UPDATE live_course_terms SET course_ends_at=now()-interval '1 day' WHERE enrollment_id=(SELECT enrollment_id FROM live_bookings WHERE id=(SELECT id FROM public_qa));
SELECT test_assert(NOT live_recording_access((SELECT id FROM live_assets WHERE title='Public workflow QA'),false),'playback ends with course');
SELECT test_assert(live_recording_access((SELECT id FROM live_assets WHERE title='Public workflow QA'),true),'download grace period survives course end');
UPDATE enrollments SET status='completed' WHERE id=(SELECT enrollment_id FROM live_bookings WHERE id=(SELECT id FROM public_qa));
SELECT test_assert(jsonb_array_length(live_library()->'assets')>0,'completed enrollment can find downloadable recording');
UPDATE enrollments SET status='revoked' WHERE id=(SELECT enrollment_id FROM live_bookings WHERE id=(SELECT id FROM public_qa));
SELECT test_assert(NOT live_recording_access((SELECT id FROM live_assets WHERE title='Public workflow QA'),true),'revocation blocks downloads');
SELECT set_config('request.jwt.claim.sub','00000000-0000-4000-8000-000000000004',false);
SELECT test_reject(format('SELECT live_recording_download_info(%L)',(SELECT id FROM live_assets WHERE title='Public workflow QA')),'expired');
SELECT test_reject($$SELECT live_enrollment_terms()$$,'Administrator');
SELECT test_assert(NOT has_table_privilege('authenticated','live_course_terms','UPDATE'),'students cannot change expiry');
SELECT test_assert((SELECT count(*)=3 FROM live_booking_notifications WHERE booking_id=(SELECT id FROM public_qa) AND event='requested'),'request queues student, teacher and admin notification');
SELECT test_assert(NOT has_table_privilege('authenticated','live_booking_notifications','SELECT'),'notification recipients and queue are private');
SELECT test_assert(NOT has_function_privilege('authenticated','claim_live_booking_notifications()','EXECUTE'),'users cannot drain email queue');
UPDATE live_bookings SET status='pending',starts_at=now()-interval '1 minute',ends_at=now()+interval '29 minutes',credit_used=true WHERE id=(SELECT replacement FROM public_qa);
SELECT prepare_live_booking_notifications();
SELECT prepare_live_booking_notifications();
SELECT test_assert((SELECT status='cancelled' AND NOT credit_used AND cancellation_reason='expired' FROM live_bookings WHERE id=(SELECT replacement FROM public_qa)),'unapproved requests expire without charging the student');
ROLLBACK;
SELECT 'PASS: approval, 48/72-hour cutoffs, refunds, atomic rescheduling and course recording/download access';
