-- Fix Kids E-book descriptions: use full descriptions with age ranges
-- so the DB description (which takes priority in EbookDetailPage) matches locale files.

-- Kids Basic (ages 5-8)
UPDATE courses SET
  description    = 'The Eduway Kids Basic e-book is specially crafted for young learners aged 5-8 who are just beginning their English adventure. Using a playful, multisensory approach with colorful visuals, songs, and interactive pages, this e-book makes learning English an exciting journey. Every page is designed with dyslexia-friendly techniques to ensure every child can succeed.',
  description_it = 'L''e-book Eduway Kids Basic è appositamente creato per giovani apprendenti dai 5 agli 8 anni che stanno iniziando la loro avventura in inglese. Con un approccio giocoso e multisensoriale, immagini colorate, canzoni e pagine interattive, questo e-book rende l''apprendimento dell''inglese un viaggio entusiasmante. Ogni pagina è progettata con tecniche adatte alla dislessia per garantire che ogni bambino possa avere successo.',
  description_sr = 'Eduway Kids Basic e-knjiga je posebno kreirana za mlade učenike uzrasta 5-8 godina koji tek započinju svoju avanturu sa engleskim jezikom. Koristeći razigrani, multisenzorni pristup sa šarenim vizuelnim sadržajima, pesmama i interaktivnim stranicama, ova e-knjiga čini učenje engleskog uzbudljivim putovanjem. Svaka stranica je osmišljena sa tehnikama prilagođenim disleksiji kako bi svako dete moglo da uspe.',
  description_es = 'El e-book Eduway Kids Basic está especialmente diseñado para jóvenes aprendices de 5 a 8 años que están comenzando su aventura con el inglés. Con un enfoque lúdico y multisensorial, con ilustraciones coloridas, canciones y páginas interactivas, este e-book convierte el aprendizaje del inglés en un viaje emocionante. Cada página está diseñada con técnicas adaptadas a la dislexia para asegurar que cada niño pueda tener éxito.'
WHERE level = 'kids-basic' AND product_type = 'ebook';

-- Kids Medium (ages 7-10)
UPDATE courses SET
  description    = 'The Eduway Kids Medium e-book builds on the basics, designed for young learners aged 7-10 who are ready to expand their English skills. Through story-based learning, creative activities, and interactive exercises, children develop reading, writing, and speaking confidence. Every page incorporates dyslexia-friendly methods to support all learning styles.',
  description_it = 'L''e-book Eduway Kids Medium si basa sulle nozioni di base, progettato per giovani apprendenti dai 7 ai 10 anni pronti ad ampliare le proprie competenze in inglese. Attraverso l''apprendimento basato su storie, attività creative ed esercizi interattivi, i bambini sviluppano sicurezza nella lettura, scrittura e nel parlato. Ogni pagina incorpora metodi adatti alla dislessia per supportare tutti gli stili di apprendimento.',
  description_sr = 'Eduway Kids Medium e-knjiga nadograđuje osnove, osmišljena za mlade učenike uzrasta 7-10 godina koji su spremni da prošire svoje veštine engleskog. Kroz učenje zasnovano na pričama, kreativne aktivnosti i interaktivne vežbe, deca razvijaju samopouzdanje u čitanju, pisanju i govoru. Svaka stranica uključuje metode prilagođene disleksiji kako bi podržala sve stilove učenja.',
  description_es = 'El e-book Eduway Kids Medium se basa en lo aprendido, diseñado para jóvenes aprendices de 7 a 10 años que están preparados para ampliar sus habilidades en inglés. A través del aprendizaje basado en historias, actividades creativas y ejercicios interactivos, los niños desarrollan confianza en la lectura, la escritura y el habla. Cada página incorpora métodos adaptados a la dislexia para apoyar todos los estilos de aprendizaje.'
WHERE level = 'kids-medium' AND product_type = 'ebook';

-- Kids Advanced (ages 9-12)
UPDATE courses SET
  description    = 'The Eduway Kids Advanced e-book is designed for confident young learners aged 9-12 who are ready to master English at a higher level. This comprehensive guide prepares students for school English requirements and Cambridge A2 Flyers exam. Complex grammar is taught through engaging contexts, and creative expression is encouraged throughout.',
  description_it = 'L''e-book Eduway Kids Advanced è progettato per giovani apprendenti sicuri dai 9 ai 12 anni pronti a padroneggiare l''inglese a un livello superiore. Questa guida completa prepara gli studenti per i requisiti di inglese scolastico e l''esame Cambridge A2 Flyers. La grammatica complessa viene insegnata attraverso contesti coinvolgenti e l''espressione creativa è incoraggiata in tutto il percorso.',
  description_sr = 'Eduway Kids Advanced e-knjiga je osmišljena za samouverene mlade učenike uzrasta 9-12 godina koji su spremni da savladaju engleski na višem nivou. Ovaj sveobuhvatni vodič priprema učenike za školske zahteve iz engleskog i Cambridge A2 Flyers ispit. Složena gramatika se predaje kroz zanimljive kontekste, a kreativno izražavanje se podstiče kroz ceo kurs.',
  description_es = 'El e-book Eduway Kids Advanced está diseñado para jóvenes aprendices seguros de sí mismos, de 9 a 12 años, que están preparados para dominar el inglés a un nivel superior. Esta guía completa prepara a los estudiantes para los requisitos de inglés escolar y el examen Cambridge A2 Flyers. La gramática compleja se enseña a través de contextos atractivos, y se fomenta la expresión creativa en todo momento.'
WHERE level = 'kids-advanced' AND product_type = 'ebook';
